#' Simulated dataset for knockofftools
#'
#' @description
#' A synthetic dataset generated by the function \code{generate_simdata()}.
#' It contains simulated Gaussian, binary, and survival outcomes along with covariates.
#'
#' @format A data frame with 2000 rows and multiple columns:
#' \describe{
#'   \item{Yg}{Numeric, Gaussian response}
#'   \item{Yb}{Factor, binary response}
#'   \item{Tc}{Survival object (time-to-event outcome)}
#'   \item{X...}{Covariates (numeric and factor)}
#' }
#'
#' @source Simulated using \code{generate_simdata()}
#'
#' @examples
#' data(simdata)
#' head(simdata)
"simdata"
