#' Simulated dataset for knockofftools
#'
#' @description
#' A synthetic dataset generated by the function \code{generate_simdata()}.
#' It contains simulated Gaussian, binary, and survival outcomes along with covariates.
#'
#' @format A data frame with 2000 rows and 33 variables:
#' \describe{
#'   \item{Tc}{Treatment indicator}
#'   \item{X1--X30}{Covariates}
#'   \item{Yb}{Binary outcome}
#'   \item{Yg}{Continuous outcome}
#' }
#'
#' @source Simulated using \code{generate_simdata()}
#'
#' @examples
#' data(simdata)
#' head(simdata)
"simdata"
